In [1]:
l = [23245, 27, 546, 215, -1234] # this is a list

In [2]:
l[0:2]

[23245, 27]

In [11]:
l[0:5:2]

[23245, 546, -1234]

Interestingly when you create a slice of a list you create a new list

In [9]:
l

[23245, 27, 546, 215, -1234]

In [5]:
import numpy as np
a = np.array(l)

In [6]:
a[2:]

array([  546,   215, -1234])

In [7]:
a[0:2]

array([23245,    27])

In [8]:
a[0:5:2]

array([23245,   546, -1234])

when you create a slice of an array you are only creating a view of the original array not a new array

In [12]:
b = a[2:4]

In [13]:
b

array([546, 215])

In [14]:
b[0]

546

so b is a view of the array a

In [15]:
b[:] = 111

In [16]:
a

array([23245,    27,   111,   111, -1234])

see how where b was 2 and 4 meaning item in space 3 and 4 or 546 and 215 from a those are now 111 in a

In [17]:
b

array([111, 111])

In [18]:
# to copy an array and rename it
c = a.copy()

In [19]:
c

array([23245,    27,   111,   111, -1234])

In [20]:
a

array([23245,    27,   111,   111, -1234])